server:
  port: 9000

# database setting
spring:
  # mail send setting
  mail:
    host: smtp.naver.com
    port: 465
    username: honda1173@naver.com
    password: NSKKTFC5STG9
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  datasource:
    url: jdbc:mariadb://localhost:3306/eventdb
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    # DBMS dialect setting
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      # ddl
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # SQL log
    database: mysql

# log level setting
logging:
  level:
    root: info
    com.study.event: debug
    org.hibernate.SQL: debug




